### ISSUE TITLE
import  Froala Editor   $(...).editable is not a function

### ISSUE THREAD

**Issue by Cydmi** [webpack/imports-loader#24]
`#{ test: require.resolve("./src/plugins/froala_editor.min"), loader: "imports?$=jQuery" } 
var ``$=require("jquery");$('#edit').editable()` 

webpack chrome console error : Uncaught TypeError: $(...).editable is not a function!

why ?

**Comment by SpaceK33z** [comment]
See [this question](http://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack) and [this question](http://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack). If that doesn't work, I would recommend to ask this question on StackOverflow since it's not an issue from this repo.

tl;dr - you might have duplicate jquery versions.
