### ISSUE TITLE
Doesn't seem to work with importing jQuery into Bootstrap

### ISSUE THREAD

**Issue by jeffcharles** [webpack/imports-loader#3]
I've installed version 3.3.1 of Bootstrap and version 1.11.1 of jQuery. In my entrypoint js file, I have:

```
require('imports?jQuery=jquery!bootstrap')
```

After building my javascript file without errors and running it in a browser I get a `Uncaught ReferenceError: jQuery is not defined` error located in the Bootstrap code.

I see an inserted jQuery definition once in https://github.com/twbs/bootstrap/blob/master/dist/js/npm.js but not in any of the modules this module imports. The imported modules are what expect jQuery to have a definition.

Is there a way to import a variable into all modules under a certain point in the dependency tree (e.g., into Bootstrap and all of the modules it depends on) but not define it globally or at least not globally to non-Bootstrap modules?

**Comment by GeraldIstar** [comment]
I've got same issuse, but not with bootstrap. I found that loader does not add `require('jquery')` for `'imports?jQuery=jquery!'` with big 'Q'. If I importing with another name or big letter - it's add `require(...)`.

**Comment by billyxs** [comment]
@jeffcharles, I had to install the imports-loader for that to work - npm install imports-loader

**Comment by bishopZ** [comment]
I am getting the same error.

**Comment by methodbox** [comment]
I have yet to find a proper way of importing jQuery in a way that doesn't break. 

I'm using Vuejs and their webpack build, but can't even simply pull this in as a static file, import or require in a way that makes jQuery accessible on all of my template modules.

Since jQuery needs to basically wrap the DOM, I can see why webpack may not be friendly with it, but even when imported as a static asset or directly in the head OR where $ is available globally, it will still throw errors at weird places.

Seems pointless to "optimize" my JS bundle if webpack still doesn't have proper ES6 support and doesn't respect blatantly obvious load order.

I've never had such a pain in the ass loading jQuery, which I would forgoe entirely if this project didn't need an image slider which is so much easier with jQuery.

**Comment by SpaceK33z** [comment]
If this still doesn't work, imports-loader might be not suited for the job. See this [StackOverflow answer](https://stackoverflow.com/questions/29878790/exposing-jquery-plugin-with-webpack/30647927#30647927) for a couple of ideas to fix this issue.
